# Generated by Django 5.0.7 on 2026-02-18 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calls', '0001_initial'),
        ('campaigns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('offline', 'Offline'), ('available', 'Available'), ('busy', 'Busy'), ('wrapup', 'Wrap-up'), ('break', 'Break'), ('lunch', 'Lunch'), ('training', 'Training'), ('meeting', 'Meeting'), ('system_issues', 'System Issues')], default='offline', max_length=20)),
                ('status_changed_at', models.DateTimeField(auto_now=True)),
                ('break_reason', models.CharField(blank=True, max_length=100)),
                ('current_call_id', models.CharField(blank=True, max_length=50)),
                ('call_start_time', models.DateTimeField(blank=True, null=True)),
                ('last_heartbeat', models.DateTimeField(blank=True, help_text='Last ping from agent browser - used for zombie detection', null=True)),
                ('wrapup_started_at', models.DateTimeField(blank=True, help_text='When agent entered wrapup status', null=True)),
                ('wrapup_call_id', models.CharField(blank=True, default='', help_text='Call ID pending disposition in wrapup', max_length=50)),
                ('current_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_agents', to='campaigns.campaign')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_status', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent Status',
                'verbose_name_plural': 'Agent Statuses',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('extension', models.CharField(blank=True, max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('is_online', models.BooleanField(default=False)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('total_calls_made', models.IntegerField(default=0)),
                ('total_calls_answered', models.IntegerField(default=0)),
                ('employee_id', models.CharField(blank=True, max_length=20)),
                ('agent_id', models.CharField(blank=True, max_length=20)),
                ('is_active_agent', models.BooleanField(default=False)),
                ('skill_level', models.CharField(default='1', max_length=50)),
                ('can_make_outbound', models.BooleanField(default=True)),
                ('can_receive_inbound', models.BooleanField(default=True)),
                ('can_transfer_calls', models.BooleanField(default=True)),
                ('can_conference_calls', models.BooleanField(default=True)),
                ('shift_start', models.TimeField(blank=True, null=True)),
                ('shift_end', models.TimeField(blank=True, null=True)),
                ('theme_preference', models.CharField(default='light', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='AgentTimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('offline', 'Offline'), ('available', 'Available'), ('busy', 'Busy/On Call'), ('wrapup', 'Wrap-up'), ('break', 'Break'), ('lunch', 'Lunch'), ('training', 'Training'), ('meeting', 'Meeting'), ('system_issues', 'System Issues')], db_index=True, max_length=20)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(db_index=True)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('call_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_logs', to='calls.calllog')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_time_logs', to='campaigns.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent Time Log',
                'verbose_name_plural': 'Agent Time Logs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='users_timelog_user_date_idx'), models.Index(fields=['user', 'status', 'date'], name='users_timelog_usr_stat_dt_idx')],
            },
        ),
    ]
