# Generated by Django 5.0.7 on 2026-02-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_agentstatus_wrapup'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentstatus',
            name='sub_status',
            field=models.CharField(
                max_length=50,
                blank=True,
                default='',
                help_text='Detailed sub-status: hold, transfer, conference, ringing, connecting, etc.'
            ),
        ),
        migrations.AddField(
            model_name='agentstatus',
            name='status_timestamp',
            field=models.DateTimeField(
                auto_now=True,
                help_text='Precise timestamp of last status change'
            ),
        ),
        migrations.AddField(
            model_name='agentstatus',
            name='call_duration_seconds',
            field=models.PositiveIntegerField(
                default=0,
                help_text='Duration of current call in seconds'
            ),
        ),
        migrations.AddField(
            model_name='agentstatus',
            name='wrapup_start_time',
            field=models.DateTimeField(
                null=True,
                blank=True,
                help_text='When agent entered wrapup status'
            ),
        ),
        migrations.AlterField(
            model_name='agentstatus',
            name='status',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('offline', 'Offline'),
                    ('available', 'Available/Idle'),
                    ('ringing', 'Ringing'),
                    ('connecting', 'Connecting'),
                    ('busy', 'In-Call'),
                    ('on_hold', 'Call On Hold'),
                    ('transferring', 'Transferring'),
                    ('conference', 'Conference'),
                    ('wrapup', 'Wrap-up/ACW'),
                    ('break', 'Break'),
                    ('lunch', 'Lunch'),
                    ('training', 'Training'),
                    ('meeting', 'Meeting'),
                    ('system_issues', 'System Issues'),
                ],
                default='offline'
            ),
        ),
    ]
