# Generated by Django 5.0.7 on 2026-02-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_agentstatus_enhanced_tracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentstatus',
            name='call_duration_seconds',
        ),
        migrations.RemoveField(
            model_name='agentstatus',
            name='status_timestamp',
        ),
        migrations.RemoveField(
            model_name='agentstatus',
            name='sub_status',
        ),
        migrations.RemoveField(
            model_name='agentstatus',
            name='wrapup_start_time',
        ),
        migrations.AlterField(
            model_name='agentstatus',
            name='status',
            field=models.CharField(choices=[('offline', 'Offline'), ('available', 'Available'), ('busy', 'Busy'), ('wrapup', 'Wrap-up'), ('break', 'Break'), ('lunch', 'Lunch'), ('training', 'Training'), ('meeting', 'Meeting'), ('system_issues', 'System Issues')], default='offline', max_length=20),
        ),
    ]
