# Generated by Django 5.0.7 on 2026-02-18 10:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadRecyclingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('source_status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('callback', 'Callback Scheduled'), ('sale', 'Sale'), ('no_answer', 'No Answer'), ('busy', 'Busy'), ('failed', 'Failed'), ('dropped', 'Dropped'), ('congestion', 'Congestion'), ('not_interested', 'Not Interested'), ('dnc', 'Do Not Call'), ('invalid', 'Invalid')], max_length=20)),
                ('target_status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('callback', 'Callback Scheduled'), ('sale', 'Sale'), ('no_answer', 'No Answer'), ('busy', 'Busy'), ('failed', 'Failed'), ('dropped', 'Dropped'), ('congestion', 'Congestion'), ('not_interested', 'Not Interested'), ('dnc', 'Do Not Call'), ('invalid', 'Invalid')], max_length=20)),
                ('days_since_contact', models.PositiveIntegerField(default=7)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Lead Recycling Rule',
                'verbose_name_plural': 'Lead Recycling Rules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeadFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('filter_criteria', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead Filter',
                'verbose_name_plural': 'Lead Filters',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeadList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('assigned_campaign', models.ForeignKey(blank=True, help_text='If set, leads in this list will be auto-queued to the campaign.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_lists', to='campaigns.campaign')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_lead_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead List',
                'verbose_name_plural': 'Lead Lists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='lead_imports/')),
                ('skip_duplicates', models.BooleanField(default=True)),
                ('check_dnc', models.BooleanField(default=True)),
                ('field_mapping', models.JSONField(blank=True, default=dict)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('processed_rows', models.PositiveIntegerField(default=0)),
                ('successful_imports', models.PositiveIntegerField(default=0)),
                ('failed_imports', models.PositiveIntegerField(default=0)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lead_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='leads.leadlist')),
            ],
            options={
                'verbose_name': 'Lead Import',
                'verbose_name_plural': 'Lead Imports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('callback', 'Callback Scheduled'), ('sale', 'Sale'), ('no_answer', 'No Answer'), ('busy', 'Busy'), ('failed', 'Failed'), ('dropped', 'Dropped'), ('congestion', 'Congestion'), ('not_interested', 'Not Interested'), ('dnc', 'Do Not Call'), ('invalid', 'Invalid')], default='new', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('call_count', models.PositiveIntegerField(default=0)),
                ('last_contact_date', models.DateTimeField(blank=True, null=True)),
                ('last_dial_attempt', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp of last dial attempt (successful or not)', null=True)),
                ('dial_result', models.CharField(blank=True, db_index=True, default='', help_text='Result of last dial attempt (answered, no_answer, busy, failed, etc.)', max_length=50)),
                ('dial_attempts', models.PositiveIntegerField(default=0, help_text='Total number of dial attempts (includes failed attempts)')),
                ('answered_count', models.PositiveIntegerField(default=0, help_text='Number of times call was answered')),
                ('last_status_change', models.DateTimeField(blank=True, help_text='When status was last changed', null=True)),
                ('comments', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, default='Manual Entry', max_length=200)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('lead_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='leads.leadlist')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField()),
                ('is_important', models.BooleanField(default=False)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='leads.lead')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead Note',
                'verbose_name_plural': 'Lead Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadRecycleRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('source_status', models.CharField(choices=[('no_answer', 'No Answer'), ('busy', 'Busy'), ('voicemail', 'Voicemail'), ('callback', 'Callback'), ('not_interested', 'Not Interested')], help_text='Recycle leads with this status', max_length=20)),
                ('target_status', models.CharField(default='new', help_text='Status to set after recycling', max_length=20)),
                ('recycle_after_hours', models.PositiveIntegerField(default=24, help_text='Hours after last contact before recycling')),
                ('max_attempts', models.PositiveIntegerField(default=5, help_text='Maximum call attempts before lead is excluded')),
                ('min_attempts', models.PositiveIntegerField(default=1, help_text='Minimum call attempts before eligible for recycle')),
                ('priority_adjustment', models.IntegerField(default=0, help_text='Adjust lead priority on recycle (+/- value)')),
                ('active_days', models.CharField(default='1,2,3,4,5', help_text='Days of week when rule is active (1=Mon, 7=Sun)', max_length=50)),
                ('active_start_hour', models.PositiveIntegerField(default=9, help_text='Hour of day when rule becomes active (0-23)')),
                ('active_end_hour', models.PositiveIntegerField(default=17, help_text='Hour of day when rule stops being active (0-23)')),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('total_recycled', models.PositiveIntegerField(default=0)),
                ('campaign', models.ForeignKey(blank=True, help_text='Leave blank to apply to all campaigns', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recycle_rules', to='campaigns.campaign')),
                ('lead_list', models.ForeignKey(blank=True, help_text='Leave blank to apply to all lists', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recycle_rules', to='leads.leadlist')),
            ],
            options={
                'verbose_name': 'Lead Recycle Rule',
                'verbose_name_plural': 'Lead Recycle Rules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeadRecycleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('old_call_count', models.PositiveIntegerField(default=0)),
                ('recycled_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recycle_logs', to='leads.lead')),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='leads.leadrecyclerule')),
            ],
            options={
                'verbose_name': 'Lead Recycle Log',
                'verbose_name_plural': 'Lead Recycle Logs',
                'ordering': ['-recycled_at'],
            },
        ),
        migrations.CreateModel(
            name='DNCEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^\\+?1?\\d{9,15}$')])),
                ('reason', models.CharField(blank=True, default='Manual Entry', max_length=200)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DNC Entry',
                'verbose_name_plural': 'DNC Entries',
                'indexes': [models.Index(fields=['phone_number'], name='leads_dncen_phone_n_3d80a6_idx')],
            },
        ),
        migrations.CreateModel(
            name='CallbackSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_time', models.DateTimeField()),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_callbacks', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_callbacks', to='campaigns.campaign')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callbacks', to='leads.lead')),
            ],
            options={
                'verbose_name': 'Callback Schedule',
                'verbose_name_plural': 'Callback Schedules',
                'ordering': ['scheduled_time'],
                'indexes': [models.Index(fields=['scheduled_time'], name='leads_callb_schedul_028e92_idx'), models.Index(fields=['agent', 'is_completed'], name='leads_callb_agent_i_dede0b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['phone_number'], name='leads_lead_phone_n_e78ed0_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status'], name='leads_lead_status_e23abe_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['last_contact_date'], name='leads_lead_last_co_c5a3be_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_user'], name='leads_lead_assigne_a9f049_idx'),
        ),
    ]
