# Generated by Django 5.0.7 on 2025-07-10 06:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('filter_criteria', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Lead Filter',
                'verbose_name_plural': 'Lead Filters',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeadRecyclingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('source_status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('callback', 'Callback Scheduled'), ('sale', 'Sale'), ('no_answer', 'No Answer'), ('busy', 'Busy'), ('not_interested', 'Not Interested'), ('dnc', 'Do Not Call'), ('invalid', 'Invalid')], max_length=20)),
                ('target_status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('callback', 'Callback Scheduled'), ('sale', 'Sale'), ('no_answer', 'No Answer'), ('busy', 'Busy'), ('not_interested', 'Not Interested'), ('dnc', 'Do Not Call'), ('invalid', 'Invalid')], max_length=20)),
                ('days_since_contact', models.PositiveIntegerField(default=7)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Lead Recycling Rule',
                'verbose_name_plural': 'Lead Recycling Rules',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='dnclist',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='leadhistory',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='leadhistory',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lead', 'verbose_name_plural': 'Leads'},
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='leads_lead_last_ca_508e1b_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='leads_lead_assigne_4b518a_idx',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='address1',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='assigned_agent',
            new_name='assigned_user',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='address2',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='last_called',
            new_name='last_contact_date',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='alt_phone',
            new_name='zip_code',
        ),
        migrations.RenameField(
            model_name='leadimport',
            old_name='error_count',
            new_name='duplicate_count',
        ),
        migrations.RenameField(
            model_name='leadimport',
            old_name='description',
            new_name='error_message',
        ),
        migrations.RenameField(
            model_name='leadimport',
            old_name='file_size',
            new_name='failed_imports',
        ),
        migrations.RenameField(
            model_name='leadimport',
            old_name='imported_leads',
            new_name='successful_imports',
        ),
        migrations.RenameField(
            model_name='leadimport',
            old_name='started_by',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='dncentry',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='lead',
            name='assigned_campaign',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='best_time_to_call',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='country',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='custom_fields',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='is_callback',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='is_dnc',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='is_priority',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='lead_id',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='next_call_time',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='title',
        ),
        migrations.RemoveField(
            model_name='leadimport',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='leadimport',
            name='error_log',
        ),
        migrations.RemoveField(
            model_name='leadimport',
            name='field_mapping',
        ),
        migrations.RemoveField(
            model_name='leadimport',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='leadimport',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='leadimport',
            name='skipped_leads',
        ),
        migrations.RemoveField(
            model_name='leadimport',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='leadimport',
            name='update_existing',
        ),
        migrations.RemoveField(
            model_name='leadlist',
            name='active_leads',
        ),
        migrations.RemoveField(
            model_name='leadlist',
            name='called_leads',
        ),
        migrations.RemoveField(
            model_name='leadlist',
            name='import_date',
        ),
        migrations.RemoveField(
            model_name='leadlist',
            name='list_id',
        ),
        migrations.RemoveField(
            model_name='leadlist',
            name='source_file',
        ),
        migrations.RemoveField(
            model_name='leadlist',
            name='total_leads',
        ),
        migrations.AddField(
            model_name='leadimport',
            name='check_dnc',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='leadimport',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='lead_imports/'),
        ),
        migrations.AddField(
            model_name='leadlist',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=500),
        ),
        migrations.AlterField(
            model_name='dncentry',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='dncentry',
            name='reason',
            field=models.CharField(blank=True, default='Manual Entry', max_length=200),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='leads.leadlist'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, default='Manual Entry', max_length=200),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('callback', 'Callback Scheduled'), ('sale', 'Sale'), ('no_answer', 'No Answer'), ('busy', 'Busy'), ('not_interested', 'Not Interested'), ('dnc', 'Do Not Call'), ('invalid', 'Invalid')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='leadimport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['last_contact_date'], name='leads_lead_last_co_c5a3be_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_user'], name='leads_lead_assigne_a9f049_idx'),
        ),
        migrations.AddField(
            model_name='leadfilter',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='LeadHistory',
        ),
        migrations.RemoveField(
            model_name='dncentry',
            name='dnc_list',
        ),
        migrations.RemoveField(
            model_name='dncentry',
            name='expires_on',
        ),
        migrations.DeleteModel(
            name='DNCList',
        ),
    ]
