# Generated by Django 5.0.7 on 2025-11-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_leadfilter_leadrecyclingrule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadimport',
            name='field_mapping',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
