# Generated by Django 5.0.7 on 2026-01-28 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0015_hopper_system'),
        ('leads', '0005_leadlist_assigned_campaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadRecycleRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('source_status', models.CharField(choices=[('no_answer', 'No Answer'), ('busy', 'Busy'), ('voicemail', 'Voicemail'), ('callback', 'Callback'), ('not_interested', 'Not Interested')], help_text='Recycle leads with this status', max_length=20)),
                ('target_status', models.CharField(default='new', help_text='Status to set after recycling', max_length=20)),
                ('recycle_after_hours', models.PositiveIntegerField(default=24, help_text='Hours after last contact before recycling')),
                ('max_attempts', models.PositiveIntegerField(default=5, help_text='Maximum call attempts before lead is excluded')),
                ('min_attempts', models.PositiveIntegerField(default=1, help_text='Minimum call attempts before eligible for recycle')),
                ('priority_adjustment', models.IntegerField(default=0, help_text='Adjust lead priority on recycle (+/- value)')),
                ('active_days', models.CharField(default='1,2,3,4,5', help_text='Days of week when rule is active (1=Mon, 7=Sun)', max_length=50)),
                ('active_start_hour', models.PositiveIntegerField(default=9, help_text='Hour of day when rule becomes active (0-23)')),
                ('active_end_hour', models.PositiveIntegerField(default=17, help_text='Hour of day when rule stops being active (0-23)')),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('total_recycled', models.PositiveIntegerField(default=0)),
                ('campaign', models.ForeignKey(blank=True, help_text='Leave blank to apply to all campaigns', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recycle_rules', to='campaigns.campaign')),
                ('lead_list', models.ForeignKey(blank=True, help_text='Leave blank to apply to all lists', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recycle_rules', to='leads.leadlist')),
            ],
            options={
                'verbose_name': 'Lead Recycle Rule',
                'verbose_name_plural': 'Lead Recycle Rules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeadRecycleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('old_call_count', models.PositiveIntegerField(default=0)),
                ('recycled_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recycle_logs', to='leads.lead')),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='leads.leadrecyclerule')),
            ],
            options={
                'verbose_name': 'Lead Recycle Log',
                'verbose_name_plural': 'Lead Recycle Logs',
                'ordering': ['-recycled_at'],
            },
        ),
    ]
