# Generated by Django 5.0.7 on 2026-02-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_leadrecyclerule_leadrecyclelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='last_dial_attempt',
            field=models.DateTimeField(
                null=True,
                blank=True,
                db_index=True,
                help_text='Timestamp of last dial attempt (successful or not)'
            ),
        ),
        migrations.AddField(
            model_name='lead',
            name='dial_result',
            field=models.CharField(
                max_length=50,
                blank=True,
                default='',
                db_index=True,
                help_text='Result of last dial attempt (answered, no_answer, busy, failed, etc.)'
            ),
        ),
        migrations.AddField(
            model_name='lead',
            name='dial_attempts',
            field=models.PositiveIntegerField(
                default=0,
                help_text='Total number of dial attempts (includes failed attempts)'
            ),
        ),
        migrations.AddField(
            model_name='lead',
            name='answered_count',
            field=models.PositiveIntegerField(
                default=0,
                help_text='Number of times call was answered'
            ),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_status_change',
            field=models.DateTimeField(
                null=True,
                blank=True,
                help_text='When status was last changed'
            ),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(
                max_length=50,
                choices=[
                    ('new', 'New'),
                    ('contacted', 'Contacted'),
                    ('callback', 'Callback Scheduled'),
                    ('sale', 'Sale'),
                    ('no_answer', 'No Answer'),
                    ('busy', 'Busy'),
                    ('failed', 'Failed'),
                    ('dropped', 'Dropped'),
                    ('congestion', 'Congestion'),
                    ('not_interested', 'Not Interested'),
                    ('dnc', 'Do Not Call'),
                    ('invalid', 'Invalid'),
                ],
                default='new',
                db_index=True
            ),
        ),
        # Add indexes for better query performance
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(
                fields=['status', 'dial_attempts', 'last_dial_attempt'],
                name='leads_lead_status_dial_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(
                fields=['lead_list', 'status'],
                name='leads_lead_list_status_idx'
            ),
        ),
    ]
