# Generated by Django 5.0.7 on 2026-02-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_lead_enhanced_tracking'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lead',
            name='leads_lead_status_dial_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='leads_lead_list_status_idx',
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('callback', 'Callback Scheduled'), ('sale', 'Sale'), ('no_answer', 'No Answer'), ('busy', 'Busy'), ('failed', 'Failed'), ('dropped', 'Dropped'), ('congestion', 'Congestion'), ('not_interested', 'Not Interested'), ('dnc', 'Do Not Call'), ('invalid', 'Invalid')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='leadrecyclingrule',
            name='source_status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('callback', 'Callback Scheduled'), ('sale', 'Sale'), ('no_answer', 'No Answer'), ('busy', 'Busy'), ('failed', 'Failed'), ('dropped', 'Dropped'), ('congestion', 'Congestion'), ('not_interested', 'Not Interested'), ('dnc', 'Do Not Call'), ('invalid', 'Invalid')], max_length=20),
        ),
        migrations.AlterField(
            model_name='leadrecyclingrule',
            name='target_status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('callback', 'Callback Scheduled'), ('sale', 'Sale'), ('no_answer', 'No Answer'), ('busy', 'Busy'), ('failed', 'Failed'), ('dropped', 'Dropped'), ('congestion', 'Congestion'), ('not_interested', 'Not Interested'), ('dnc', 'Do Not Call'), ('invalid', 'Invalid')], max_length=20),
        ),
    ]
