# Generated by Django 5.2.4 on 2025-11-07 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('campaigns', '0003_alter_campaign_campaign_id'),
        ('telephony', '0006_psendpoint_mailboxes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentDialerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_extension', models.CharField(max_length=20)),
                ('agent_channel_id', models.CharField(blank=True, max_length=100)),
                ('agent_bridge_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('connecting', 'Connecting'), ('ready', 'Ready'), ('offline', 'Offline'), ('error', 'Error')], default='connecting', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialer_sessions', to=settings.AUTH_USER_MODEL)),
                ('asterisk_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telephony.asteriskserver')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'Agent Dialer Session',
                'verbose_name_plural': 'Agent Dialer Sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
