# Generated by Django 5.0.7 on 2025-11-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agentdialersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdialersession',
            name='last_state_change',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
