# Generated by Django 5.0.7 on 2025-12-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agentdialersession_last_state_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdialersession',
            name='average_handle_time',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Average handle time in seconds', max_digits=8),
        ),
        migrations.AddField(
            model_name='agentdialersession',
            name='calls_handled',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agentdialersession',
            name='last_call_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentdialersession',
            name='total_talk_time',
            field=models.PositiveIntegerField(default=0, help_text='Total talk time in seconds'),
        ),
        migrations.AddField(
            model_name='agentdialersession',
            name='wrapup_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
