# Generated by Django 5.0.7 on 2026-02-18 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calls', '0001_initial'),
        ('campaigns', '0001_initial'),
        ('leads', '0001_initial'),
        ('telephony', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsession',
            name='current_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='agentpause',
            name='agent_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pauses', to='calls.agentsession'),
        ),
        migrations.AddField(
            model_name='calllog',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_calls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calllog',
            name='asterisk_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='telephony.asteriskserver'),
        ),
        migrations.AddField(
            model_name='calllog',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_calls', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='calllog',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='telephony.carrier'),
        ),
        migrations.AddField(
            model_name='calllog',
            name='disposition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disposition_calls', to='campaigns.disposition'),
        ),
        migrations.AddField(
            model_name='calllog',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_calls', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='callevent',
            name='call_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='calls.calllog'),
        ),
        migrations.AddField(
            model_name='callnote',
            name='call_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='calls.calllog'),
        ),
        migrations.AddField(
            model_name='callnote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='callquality',
            name='call_log',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_metrics', to='calls.calllog'),
        ),
        migrations.AddField(
            model_name='callqualityscore',
            name='call',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_details', to='calls.calllog'),
        ),
        migrations.AddField(
            model_name='callqualityscore',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='callrecordingrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recording_requests_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='callrecordingrequest',
            name='call_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recording_requests', to='calls.calllog'),
        ),
        migrations.AddField(
            model_name='callrecordingrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recording_requests_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conference',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conferences_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conferenceparticipant',
            name='call_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calls.calllog'),
        ),
        migrations.AddField(
            model_name='conferenceparticipant',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calls.conference'),
        ),
        migrations.AddField(
            model_name='conference',
            name='participants',
            field=models.ManyToManyField(related_name='conferences', through='calls.ConferenceParticipant', to='calls.calllog'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='from_agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transfer',
            name='new_call',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_transfers', to='calls.calllog'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='original_call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_transfers', to='calls.calllog'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='to_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['call_id'], name='calls_calll_call_id_b463c5_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['called_number'], name='calls_calll_called__f236dc_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['agent', 'start_time'], name='calls_calll_agent_i_147eb9_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['campaign', 'start_time'], name='calls_calll_campaig_25defe_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['start_time'], name='calls_calll_start_t_937921_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conferenceparticipant',
            unique_together={('conference', 'call_log')},
        ),
    ]
