# Generated by Django 5.0.7 on 2025-07-04 12:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('category', models.CharField(choices=[('sale', 'Sale'), ('callback', 'Callback'), ('no_answer', 'No Answer'), ('busy', 'Busy'), ('not_interested', 'Not Interested'), ('dnc', 'Do Not Call'), ('wrong_number', 'Wrong Number'), ('answering_machine', 'Answering Machine'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_sale', models.BooleanField(default=False)),
                ('requires_callback', models.BooleanField(default=False)),
                ('callback_delay', models.PositiveIntegerField(default=3600, help_text='Callback delay in seconds')),
                ('removes_from_campaign', models.BooleanField(default=False)),
                ('adds_to_dnc', models.BooleanField(default=False)),
                ('color', models.CharField(default='#6c757d', help_text='Hex color code', max_length=7)),
                ('hotkey', models.CharField(blank=True, help_text='Single character hotkey', max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Disposition',
                'verbose_name_plural': 'Dispositions',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('campaign_id', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('campaign_type', models.CharField(choices=[('outbound', 'Outbound'), ('inbound', 'Inbound'), ('blended', 'Blended')], default='outbound', max_length=20)),
                ('dial_method', models.CharField(choices=[('manual', 'Manual'), ('preview', 'Preview'), ('progressive', 'Progressive'), ('predictive', 'Predictive'), ('auto', 'Auto')], default='preview', max_length=20)),
                ('status', models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('archived', 'Archived')], default='inactive', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('daily_start_time', models.TimeField(default='09:00:00')),
                ('daily_end_time', models.TimeField(default='17:00:00')),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('call_timeout', models.PositiveIntegerField(default=30, help_text='Timeout in seconds')),
                ('retry_delay', models.PositiveIntegerField(default=3600, help_text='Delay between retries in seconds')),
                ('dial_ratio', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('max_lines', models.PositiveIntegerField(default=10)),
                ('abandon_rate', models.DecimalField(decimal_places=2, default=3.0, max_digits=5)),
                ('enable_recording', models.BooleanField(default=True)),
                ('recording_delay', models.PositiveIntegerField(default=0, help_text='Recording delay in seconds')),
                ('monitor_agents', models.BooleanField(default=False)),
                ('lead_order', models.CharField(choices=[('down', 'Down (Sequential)'), ('up', 'Up (Reverse)'), ('random', 'Random'), ('oldest_first', 'Oldest First'), ('newest_first', 'Newest First')], default='down', max_length=20)),
                ('use_internal_dnc', models.BooleanField(default=True)),
                ('use_campaign_dnc', models.BooleanField(default=False)),
                ('amd_enabled', models.BooleanField(default=False, help_text='Answering Machine Detection')),
                ('total_leads', models.PositiveIntegerField(default=0)),
                ('leads_called', models.PositiveIntegerField(default=0)),
                ('leads_remaining', models.PositiveIntegerField(default=0)),
                ('calls_today', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('max_calls_per_day', models.PositiveIntegerField(blank=True, null=True)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('calls_made', models.PositiveIntegerField(default=0)),
                ('calls_answered', models.PositiveIntegerField(default=0)),
                ('sales_made', models.PositiveIntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaign Agent',
                'verbose_name_plural': 'Campaign Agents',
                'unique_together': {('campaign', 'user')},
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='assigned_users',
            field=models.ManyToManyField(related_name='assigned_campaigns', through='campaigns.CampaignAgent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('script_type', models.CharField(choices=[('opening', 'Opening Script'), ('main', 'Main Script'), ('objection', 'Objection Handling'), ('closing', 'Closing Script'), ('callback', 'Callback Script')], default='main', max_length=20)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('campaigns', models.ManyToManyField(blank=True, related_name='scripts', to='campaigns.campaign')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Script',
                'verbose_name_plural': 'Scripts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CampaignHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_hours', to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'Campaign Hours',
                'verbose_name_plural': 'Campaign Hours',
                'ordering': ['day_of_week'],
                'unique_together': {('campaign', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='CampaignStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('calls_made', models.PositiveIntegerField(default=0)),
                ('calls_answered', models.PositiveIntegerField(default=0)),
                ('calls_dropped', models.PositiveIntegerField(default=0)),
                ('leads_processed', models.PositiveIntegerField(default=0)),
                ('leads_dispositioned', models.PositiveIntegerField(default=0)),
                ('total_talk_time', models.PositiveIntegerField(default=0, help_text='Total talk time in seconds')),
                ('total_wait_time', models.PositiveIntegerField(default=0, help_text='Total wait time in seconds')),
                ('contact_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('average_call_duration', models.PositiveIntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'Campaign Statistics',
                'verbose_name_plural': 'Campaign Statistics',
                'ordering': ['-date'],
                'unique_together': {('campaign', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CampaignDisposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositions', to='campaigns.campaign')),
                ('disposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.disposition')),
            ],
            options={
                'ordering': ['sort_order'],
                'unique_together': {('campaign', 'disposition')},
            },
        ),
    ]
