# Generated by Django 5.0.7 on 2025-07-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='timezone',
            field=models.CharField(choices=[('UTC', 'UTC (Coordinated Universal Time)'), ('America/New_York', 'Eastern Time (ET)'), ('America/Chicago', 'Central Time (CT)'), ('America/Denver', 'Mountain Time (MT)'), ('America/Los_Angeles', 'Pacific Time (PT)'), ('America/Phoenix', 'Arizona Time (MST)'), ('America/Anchorage', 'Alaska Time (AKST)'), ('Pacific/Honolulu', 'Hawaii Time (HST)'), ('Asia/Kolkata', 'India Standard Time (IST)'), ('Europe/London', 'Greenwich Mean Time (GMT)'), ('Europe/Paris', 'Central European Time (CET)'), ('Asia/Tokyo', 'Japan Standard Time (JST)'), ('Asia/Shanghai', 'China Standard Time (CST)'), ('Australia/Sydney', 'Australian Eastern Time (AEST)')], default='UTC', max_length=50),
        ),
    ]
