# Generated by Django 5.0.7 on 2025-07-09 09:02

import campaigns.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_campaign_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='campaign_id',
            field=models.CharField(default=campaigns.models.generate_uuid, editable=False, max_length=50, unique=True),
        ),
    ]
