# Generated by Django 5.2.4 on 2025-11-07 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_alter_campaign_campaign_id'),
        ('leads', '0002_leadfilter_leadrecyclingrule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dialing', 'Dialing'), ('answered', 'Answered'), ('failed', 'Failed'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_tried_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_queue', to='campaigns.campaign')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.lead')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['campaign', 'status'], name='campaigns_o_campaig_d11de5_idx'), models.Index(fields=['status', 'last_tried_at'], name='campaigns_o_status_fd3fac_idx')],
            },
        ),
    ]
