# Generated by Django 5.2.4 on 2025-11-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_outboundqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='dial_prefix',
            field=models.CharField(blank=True, help_text='Optional prefix to prepend to dialed numbers', max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='outbound_trunk',
            field=models.CharField(blank=True, help_text='Optional PJSIP trunk name for external dialing (e.g., mytrunk)', max_length=100),
        ),
    ]
