# Generated by Django 5.2.4 on 2025-11-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_campaign_dial_prefix_campaign_outbound_trunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='custom_dials_per_agent',
            field=models.PositiveIntegerField(default=1, help_text='Used when dial_speed=custom'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='dial_speed',
            field=models.CharField(choices=[('slow', 'Slow'), ('normal', 'Normal'), ('fast', 'Fast'), ('very_fast', 'Very Fast'), ('custom', 'Custom')], default='normal', max_length=20),
        ),
    ]
