# Generated by Django 5.2.4 on 2025-11-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_campaign_custom_dials_per_agent_campaign_dial_speed'),
        ('telephony', '0006_psendpoint_mailboxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='outbound_trunks',
            field=models.ManyToManyField(blank=True, help_text='Select one or more trunks (carriers) for outbound dialing.', related_name='campaigns', to='telephony.carrier'),
        ),
    ]
