# Generated by Django 5.2.4 on 2025-11-07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_campaign_outbound_trunks'),
        ('telephony', '0006_psendpoint_mailboxes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignCarrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weight', models.PositiveIntegerField(default=1)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_carriers', to='campaigns.campaign')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrier_campaigns', to='telephony.carrier')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('campaign', 'carrier')},
            },
        ),
    ]

