# Generated by Django 5.2.4 on 2025-11-07 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_campaigncarrier'),
        ('telephony', '0009_psregistration_carrier_dial_prefix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='outbound_carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_campaigns', to='telephony.carrier'),
        ),
    ]
