# Generated by Django 5.2.4 on 2025-11-07 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_campaign_outbound_carrier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='outbound_trunk',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='outbound_trunks',
        ),
    ]
