# Generated by Django 5.0.7 on 2025-11-28 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0011_outboundqueue_disposition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outboundqueue',
            name='disposition',
        ),
        migrations.RemoveField(
            model_name='outboundqueue',
            name='wrapup_at',
        ),
    ]
