# Generated by Django 5.0.7 on 2025-11-28 11:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_initial'),
        ('campaigns', '0014_campaign_wrapup_timeout'),
        ('leads', '0005_leadlist_assigned_campaign'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='dial_level',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Predictive dial multiplier: calls per available agent (e.g., 1.5 = 1.5 calls per agent)', max_digits=4),
        ),
        migrations.AddField(
            model_name='campaign',
            name='dial_timeout',
            field=models.PositiveIntegerField(default=30, help_text='Seconds to wait for call answer before considering failed'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='hopper_level',
            field=models.PositiveIntegerField(default=100, help_text='Target number of leads to maintain in hopper (refills when below this)'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='local_call_time',
            field=models.BooleanField(default=True, help_text='Respect lead timezone for calling hours'),
        ),
        migrations.AddField(
            model_name='campaignstats',
            name='drop_count',
            field=models.PositiveIntegerField(default=0, help_text='Calls answered by customer but no agent available (compliance metric)'),
        ),
        migrations.CreateModel(
            name='DialerHopper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=32)),
                ('priority', models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('status', models.CharField(choices=[('new', 'New'), ('locked', 'Locked'), ('dialing', 'Dialing'), ('completed', 'Completed'), ('dropped', 'Dropped'), ('failed', 'Failed')], default='new', max_length=20)),
                ('hopper_entry_time', models.DateTimeField(auto_now_add=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('dialed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('channel_id', models.CharField(blank=True, max_length=100)),
                ('call_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calls.calllog')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hopper_entries', to='campaigns.campaign')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hopper_entries', to='leads.lead')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_hopper_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dialer Hopper Entry',
                'verbose_name_plural': 'Dialer Hopper Entries',
                'ordering': ['-priority', 'hopper_entry_time'],
                'indexes': [models.Index(fields=['campaign', 'status', '-priority'], name='campaigns_d_campaig_20eb8d_idx'), models.Index(fields=['status', 'hopper_entry_time'], name='campaigns_d_status_086ae0_idx'), models.Index(fields=['campaign', 'lead'], name='campaigns_d_campaig_8245e5_idx')],
            },
        ),
    ]
