# Generated by Django 5.0.7 on 2026-01-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0015_hopper_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='agent_hourly_cost',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=6),
        ),
        migrations.AddField(
            model_name='campaign',
            name='amd_action',
            field=models.CharField(choices=[('hangup', 'Hangup'), ('voicemail', 'Drop Voicemail'), ('transfer', 'Transfer')], default='hangup', max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='avg_talk_time',
            field=models.IntegerField(default=180),
        ),
        migrations.AddField(
            model_name='campaign',
            name='cost_per_minute',
            field=models.DecimalField(decimal_places=4, default=0.03, max_digits=6),
        ),
        migrations.AddField(
            model_name='campaign',
            name='dial_mode',
            field=models.CharField(choices=[('predictive', 'Predictive'), ('progressive', 'Progressive'), ('power', 'Power'), ('preview', 'Preview')], default='predictive', max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='max_dial_ratio',
            field=models.FloatField(default=3.0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='revenue_per_sale',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_abandon_rate',
            field=models.FloatField(default=3.0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='voicemail_file',
            field=models.FileField(blank=True, null=True, upload_to='voicemail/'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='wrapup_time',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='amd_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
