# Generated by Django 5.0.7 on 2026-02-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0016_campaign_agent_hourly_cost_campaign_amd_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='auto_wrapup_enabled',
            field=models.BooleanField(
                default=False,
                help_text='Automatically dispose calls after wrapup timeout'
            ),
        ),
        migrations.AddField(
            model_name='campaign',
            name='auto_wrapup_timeout',
            field=models.PositiveIntegerField(
                default=120,
                help_text='Seconds before auto-wrapping up (default: 120 seconds / 2 minutes)'
            ),
        ),
        migrations.AddField(
            model_name='campaign',
            name='auto_wrapup_disposition',
            field=models.CharField(
                max_length=50,
                blank=True,
                default='not_dispositioned',
                help_text='Disposition status to apply on auto-wrapup'
            ),
        ),
    ]
