# Generated by Django 5.0.7 on 2026-02-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0017_campaign_auto_wrapup_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='auto_wrapup_disposition',
            field=models.CharField(default='not_dispositioned', help_text='Disposition code to apply on auto-wrapup', max_length=50),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='auto_wrapup_enabled',
            field=models.BooleanField(default=False, help_text='Automatically dispose calls after timeout period'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='auto_wrapup_timeout',
            field=models.PositiveIntegerField(default=120, help_text='Seconds before call is auto-dispositioned'),
        ),
    ]
