# Generated by Django 5.0.7 on 2025-07-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0002_asterisk_realtime_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extensionstable',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
