# Generated by Django 5.0.7 on 2025-07-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0003_alter_extensionstable_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='psendpoint',
            name='force_rport',
            field=models.CharField(blank=True, default='yes', max_length=3),
        ),
        migrations.AddField(
            model_name='psendpoint',
            name='rewrite_contact',
            field=models.CharField(blank=True, default='yes', max_length=3),
        ),
        migrations.AlterField(
            model_name='phone',
            name='secret',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
