# Generated by Django 5.0.7 on 2025-07-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0004_psendpoint_force_rport_psendpoint_rewrite_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SipBuddy',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=40)),
                ('secret', models.CharField(max_length=40)),
                ('host', models.CharField(default='dynamic', max_length=31)),
                ('context', models.CharField(default='agents', max_length=40)),
                ('type', models.CharField(default='friend', max_length=6)),
                ('nat', models.CharField(default='force_rport,comedia', max_length=20)),
                ('qualify', models.CharField(default='yes', max_length=7)),
                ('canreinvite', models.CharField(default='no', max_length=3)),
                ('disallow', models.CharField(default='all', max_length=200)),
                ('allow', models.CharField(default='ulaw,alaw', max_length=200)),
            ],
            options={
                'db_table': 'sip_buddies',
                'managed': True,
            },
        ),
    ]
