# Generated by Django 5.2.4 on 2025-11-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0005_sipbuddy'),
    ]

    operations = [
        migrations.AddField(
            model_name='psendpoint',
            name='mailboxes',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
