# Generated by Django 5.2.4 on 2025-11-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0006_psendpoint_mailboxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='psaor',
            name='contact',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]

