# Generated by Django 5.2.4 on 2025-11-07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0007_psaor_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='did',
            name='carrier',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='dids',
                to='telephony.carrier'
            ),
        ),
    ]
