# Generated by Django 5.2.4 on 2025-11-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0008_alter_did_carrier_related_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsRegistration',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('transport', models.CharField(blank=True, default='transport-udp', max_length=40)),
                ('server_uri', models.CharField(max_length=256)),
                ('client_uri', models.CharField(max_length=256)),
                ('contact_user', models.CharField(blank=True, max_length=80)),
                ('outbound_auth', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'ps_registrations',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='carrier',
            name='dial_prefix',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='carrier',
            name='dial_timeout',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='carrier',
            name='registration_type',
            field=models.CharField(choices=[('ip', 'IP Based'), ('registration', 'Registration Based')], default='ip', max_length=20),
        ),
    ]
