# Generated by Django 5.0.7 on 2025-11-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0009_psregistration_carrier_dial_prefix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='password',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
