# Generated by Django 5.0.7 on 2026-02-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0010_alter_carrier_password_alter_carrier_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='psendpoint',
            name='webrtc',
            field=models.CharField(blank=True, default='no', max_length=3),
        ),
    ]
