# Generated by Django 5.0.7 on 2026-02-13 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0011_psendpoint_webrtc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psendpoint',
            name='webrtc',
        ),
    ]
