# Generated by Django 5.0.7 on 2026-02-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0012_remove_psendpoint_webrtc'),
    ]

    operations = [
        migrations.AddField(
            model_name='psendpoint',
            name='dtls_setup',
            field=models.CharField(blank=True, default='actpass', max_length=20),
        ),
        migrations.AddField(
            model_name='psendpoint',
            name='dtls_verify',
            field=models.CharField(blank=True, default='fingerprint', max_length=20),
        ),
        migrations.AddField(
            model_name='psendpoint',
            name='ice_support',
            field=models.CharField(blank=True, default='yes', max_length=3),
        ),
        migrations.AddField(
            model_name='psendpoint',
            name='media_encryption',
            field=models.CharField(blank=True, default='dtls', max_length=20),
        ),
        migrations.AddField(
            model_name='psendpoint',
            name='media_use_received_transport',
            field=models.CharField(blank=True, default='yes', max_length=3),
        ),
        migrations.AddField(
            model_name='psendpoint',
            name='rtcp_mux',
            field=models.CharField(blank=True, default='yes', max_length=3),
        ),
        migrations.AddField(
            model_name='psendpoint',
            name='use_avpf',
            field=models.CharField(blank=True, default='yes', max_length=3),
        ),
        migrations.AddField(
            model_name='psendpoint',
            name='webrtc',
            field=models.CharField(blank=True, default='yes', max_length=3),
        ),
    ]
